### ISSUE TITLE
Add GTFS Data Import Functionality

### ISSUE THREAD

**Issue by ZaneBartlett1** [DartExplore/dart-explore-backend#26]
The goal of this task is to take a text file that's been cleaned up from gtfs data and import it into our database.

  - [x] Create txt file for station and station connections.
  - [x] Create a new service class GTFSImportService.
  - [x] Map txt file data to Java objects.
  - [x] Create necessary repositories to save mapped objects
  - [x] Save the Java objects to the database using repositories.

**Comment by ZaneBartlett1** [comment]
@gpennell , can you remind me where the dart info for that kind of stuff is? I remember there being files with the information about stations, stops, etc were at.

**Comment by Nightwing52** [comment]
The API can be found at this [website](https://transitfeeds.com/api/).

I did some looking around and found this [page](https://transitfeeds.com/p/dart/26/latest/routes). It is not super intuitive but for each line you want to do the following: details -> select a date -> details. You should now see the stations of your chosen line listed in order. There is also some timing data as well. Hope this helps.

**Comment by Nightwing52** [comment]
So in this file are *all* the stops in the DART system (bus and rail). You'll have to filter out the bus stops but the rail data is there with the positioning data. Let me know if you need any help. One thing I noticed is that all the rail stations have STATION in their name while all the bus stops are of the form street @ street.

https://openmobilitydata-data.s3-us-west-1.amazonaws.com/public/feeds/dart/26/20230420/original/stops.txt

**Comment by ZaneBartlett1** [comment]
So I was talking to @gpennell about this @Nightwing52 , and he's going to ask one of his friends about how they're sourcing the GTFS data since that site seems like it's a bit weird. 

When I try to find their github it's like gone, it looks like it was transferred from some other organization, and some other stuff. I'm not fully opposed to using that for the data, but it does seem like something that's going to vanish at any time. I literally can't trace any of it back to source, it's all broken links everywhere.

**Comment by Nightwing52** [comment]
I recommend downloading that text file linked in my last comment if you can't figure it out within a couple days. We are going to need this data very soon because Garrett will need it on his end.

**Comment by Nightwing52** [comment]
@ZaneBartlett1, any update on this?

**Comment by ZaneBartlett1** [comment]
Yeah I talked to @gpennell and he's still working to get it. I'll go ahead and assume that the data is the same for now and start to work on this today or tomorrow at the latest.

**Comment by Nightwing52** [comment]
Okay, sounds good. It shouldn't be too hard to scrape the data if worse comes to worse. Remember, since the stations are listed in sequential order in one of those links that also gives you the station connection data.

**Comment by ZaneBartlett1** [comment]
Btw if you follow the steps here 

> The API can be found at this [website](https://transitfeeds.com/api/).

It takes you to a 404 page on github. Like I mentioned, that whole site is sus, *but* I do think the gtfs data is valid.

I don't think we'll get anything better soon and I'd prefer not to webscrape right now, so I'll just use the gtfs data. If in the future we find something else or we need to scrape, we can do that, but that gtfs looks valid (fucking somehow) and it's available right now. So I'm going to use that.
