### ISSUE TITLE
Make a small test database.

### ISSUE THREAD

**Issue by Nightwing52** [DartExplore/dart-explore-backend#28]
We should make a small test database so that we can do unit and integration tests with our code.

**Comment by ZaneBartlett1** [comment]
Just to make sure I'm on the page with this from when we talked about it. Right now, you're making a mysql test database since you don't have docker set up, and setting up the same schema? Or did I forget something?

**Comment by Nightwing52** [comment]
This will be closed by branch [repositoryInitialDesign](https://github.com/DartExplore/dart-explore-backend/tree/repositoryInitialDesign) when merged.

**Comment by ZaneBartlett1** [comment]
I'm fairly skeptical that the SQL statements will be the exact same between the two, but as long as we agree to eventually get things to being a postgress database, then I'm all good with whatever in the meantime.

**Comment by Nightwing52** [comment]
Gotcha. I'm not too familiar with Postgres but I tried my best to write fairly neutral script. Try it on your machine and let me know if it works. You shouldn't have to make many changes. You do need to figure out how to run it though because that's how we're going to run tests next week. But going forward we'll want to start using the ORM to input data. For example, I would like to have a class that generates the DART system database (the stations and connections).

**Comment by ZaneBartlett1** [comment]
It's absolutely a MySQL database, which is what I don't want in the long run. I am able to get it working so once you update your computer we can get docker set up and convert this to a Postgres, which I do want to do. I spent a bit of time looking into the two and don't trust/like MySQL at this point lol.
