### ISSUE TITLE
Transfer datasource properties to environment variables

### ISSUE THREAD

**Issue by Nightwing52** [DartExplore/dart-explore-backend#32]
We need to transfer the datasource properties like url, username, and password to environment variables to avoid breaking each others' setups and for security reasons.

**Comment by ZaneBartlett1** [comment]
Absolutely, just one of those things I'm more concerned about doing when we move to hosting, but yes, in full agreement that it will need to happen

**Comment by Nightwing52** [comment]
Yeah I don't think there's much urgency at the moment.
