### ISSUE TITLE
Add cascade types to relationships.

### ISSUE THREAD

**Issue by Nightwing52** [DartExplore/dart-explore-backend#33]
Currently no operations are cascaded. We need to add cascade types for easier data manipulation. Cascade type is specified on the relationship annotation (@ManyToOne, @OneToMany, @ManyToMany) and the possible options are listed [here](https://www.baeldung.com/jpa-cascade-types).

**Comment by Nightwing52** [comment]
I was doing some reading and I am not sure what Cascade operations we might be interested in applying. Like, if we delete a station we probably want to delete the POIs associated with it but stations never get deleted anyways (well at least in production).The entire top half of the database (as per the diagram) never changes. We can probably actually just close this as not needed. Let me know what you think.

**Comment by ZaneBartlett1** [comment]
Wouldn't we still want cascading for things like POI to amenities though? If I delete a point of interest, we'd want to delete the records of it's mapping to any amenities on the linked table, right?

**Comment by Nightwing52** [comment]
My understanding is that in this case it would delete the Amenity. I'm not 100% sure. This is something I would test out for yourself. I'm not super sure on these things.

**Comment by ZaneBartlett1** [comment]
Just tried this, at least within the database, if you try to delete a point of interest that has a relationship in the poi_amenity table, it throws an error because it relies on it. 

I also realize we probably actually want to test this at the software level, but I feel like it's pretty indicative that we probably will have to add that.

**Comment by Nightwing52** [comment]
Thanks for adding them at the database level. The same information should be reflected at the entity level. Since you already did the work on the database side of things it should be straightforward to add the appropriate cascade types in the entities.

**Comment by ZaneBartlett1** [comment]
I haven't actually updated anything for cascading yet. I was unsure if I needed to do it at the database level if we were doing it in the ORM.

**Comment by Nightwing52** [comment]
Ah, gotcha. Was reading very quickly. Both would be nice but the ORM at the least. I agree that some changes do need to be cascaded.

**Comment by ZaneBartlett1** [comment]
So like most things, this gets more complicated. 

With doing things like saving or editing a child object through their parent object (i.e. adding a POI through station, adding an amenity through POI, etc) this is pretty easily with cascade type persist and merge. 

For one to many relationships, the cascade type remove works how you'd imagine, and will automatically delete all the child entities automatically.

For many to many relationships, from the owning side, this is handled automatically and how you would expect, basically the exact same as what the cascade type remove will do on one to many. 

The opposite however, is not true, and this will have to be handled at the service layer. For example, if we wanted to delete an amenity, we would have to manually for loop through and remove each POI that has a relationship with that amenity, then delete the amenity. Read more here - https://stackoverflow.com/questions/1082095/how-to-remove-entity-with-manytomany-relationship-in-jpa-and-corresponding-join

I am about to merge in the changes for all the above cascading options that make sense. For doing removes from the none owning side, I'll leave that to you making a service class for it, but it's a fairly low priority.
