### ISSUE TITLE
Make color table a table of Strings.

### ISSUE THREAD

**Issue by Nightwing52** [DartExplore/dart-explore-backend#36]
I recommend making the color table a table of Strings and persisting them in Java as an enum with the four colors BLUE, RED, ORANGE, and GREEN.

**Comment by Nightwing52** [comment]
This will be closed by branch [repositoryInitialDesign](https://github.com/DartExplore/dart-explore-backend/tree/repositoryInitialDesign) when merged.

**Comment by ZaneBartlett1** [comment]
I'd prefer to store them however they're listed in the GTFS data we get, if it's like that, then that works, if it's hexcolors, I'd prefer that. Let me know if I'm misunderstanding anything

**Comment by Nightwing52** [comment]
Either way is perfectly valid. I'm just thinking more from an API standpoint @gpennell could just say "I want all the stations on the GREEN line" and it's more intelligible that way. There's also only four colors.
