### ISSUE TITLE
Implement repository layer

### ISSUE THREAD

**Issue by Nightwing52** [DartExplore/dart-explore-backend#51]
The following methods should be available.
- Get list of POIs with list of given amenities.
- Get stations on a given line.
- Get list of POIs by station name.
- Get list of POIs by station name with list of given amenities.

**Comment by Nightwing52** [comment]
With #78 all you have to do is write the queries in the respective repositories.

**Comment by ZaneBartlett1** [comment]
I was having a hell of a time jumping back and forth between this issue and #38, so I split this up into individual issues and am going to close this and #38 from here. This also helps to make sure we don't work on the same tests
https://github.com/DartExplore/dart-explore-backend/issues/87
https://github.com/DartExplore/dart-explore-backend/issues/86
https://github.com/DartExplore/dart-explore-backend/issues/85
https://github.com/DartExplore/dart-explore-backend/issues/84
